FROM itdoginfo/openwrt-sdk-apk:25.12.3

ARG PODKOP_VERSION
ENV PODKOP_VERSION=${PODKOP_VERSION}
ENV PODKOP_PACKAGE_FORMAT=apk

COPY ./podkop /builder/package/feeds/utilities/podkop-plus
COPY ./luci-app-podkop-plus /builder/package/feeds/luci/luci-app-podkop-plus

RUN make defconfig && \
    make package/podkop-plus/compile -j4 V=s && \
    make package/luci-app-podkop-plus/compile -j4 V=s
